### ISSUE TITLE
bug: shapeshift 3.5.0 imports fast-deep-equal wrong breaking it

### ISSUE THREAD

**Issue by RioTheD3v** [sapphiredev/shapeshift#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

when you use type module in package.json
shapeshift imports fast-deep-equal as
import fastDeepEqual from "fast-deep-equal/es6";
breaking it
changing the code to 
import fastDeepEqual from "fast-deep-equal";
fixes it.

### Steps To Reproduce

set the type to module

### Expected behavior

it shouldnt crash

### Screenshots

![image](https://user-images.githubusercontent.com/65626921/178332994-f6d5e30e-2fbc-48b7-8a8f-c42a6af04076.png)

**Comment by imranbarbhuiya** [comment]
#155 will fix it
