### ISSUE TITLE
bug:  Type 'T' does not satisfy the constraint 'object'

### ISSUE THREAD

**Issue by davidkhierl** [sapphiredev/shapeshift#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

On build it throws an error
![image](https://user-images.githubusercontent.com/25083033/190529138-96acc39e-9daf-4efe-a16e-5b7d34028557.png)

### Steps To Reproduce

not sure how to reproduce, after updating to latest version I run into this error, the package is not installed as a dependency on my project but seems being used by library I used which I'm not sure which one

### Expected behavior

should not throw an error

**Comment by imranbarbhuiya** [comment]
a fix for this is already released. Either ask your lib maintainers to update shapeshift and release a new version or u can do either of 2 things

- Pin typescript to 4.7.x
- add override/resolutions of shapeshift to 3.6.0
