### ISSUE TITLE
request: add `s.string.phone` to regex validate a phone number

### ISSUE THREAD

**Issue by favna** [sapphiredev/shapeshift#200]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

We have `s.string.email` and in forms it is often required to enter both an email and a phone number so lets also add `s.string.phone`

### Desired solution

- Add a new validation `s.string.phone`
- Add unit tests

### Alternatives considered

Using `s.string.regex` with the regex for a phone number, however this is not ideal because then end-users have to constantly look up the phone regex online

### Additional context

Refer to https://ihateregex.io/expr/phone/ for an example for a phone regex

**Comment by imranbarbhuiya** [comment]
I'm working on it
