### ISSUE TITLE
request: cloudflare worker support

### ISSUE THREAD

**Issue by KhafraDev** [sapphiredev/shapeshift#248]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

when bundling with cloudflare workers, I get an error:

```
    ../../node_modules/@sapphire/shapeshift/dist/index.mjs:2:24:
      2 │ import { inspect } from 'node:util';
        ╵                         ~~~~~~~~~~~

  The package "node:util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, 
which will remove this error.


X [ERROR] Build failed with 1 error:

  ../../node_modules/@sapphire/shapeshift/dist/index.mjs:2:24: ERROR: Could not resolve "node:util"
```

### Desired solution

all that's needed is to remove the `node:` prefix, then the node_compat flag can actually work. Yeah it's really annoying.

### Alternatives considered

using another library I guess

**Comment by favna** [comment]
Urgh... Frigging CF. The `node:` prefix is really stylistically better. 

Wdyt @vladfrangu ?

**Comment by vladfrangu** [comment]
One of these days we should move away from importing anything from node: modules and implement them ourselves...

For now lets just drop the prefix I guess :(

**Comment by favna** [comment]
Can you make a PR for this @KhafraDev ?

**Comment by kyranet** [comment]
Part of what would be the proper fix, is to have a build that completely skips all `node:`-dependent code, aka removes the `inspect` imports and all of the inspect overrides on errors.

**Comment by favna** [comment]
Considering we want Shapeshift to be browser compatible again in due time we do indeed need to eventually remove all native dependencies but idk how to do `inspect` in browsers.
