### ISSUE TITLE
request: refactor code in order to rely less on type casting

### ISSUE THREAD

**Issue by favna** [sapphiredev/shapeshift#43]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

In a lot of cases we need to add type casts to our code because of the way it is set up. This makes development really annoying and it also removes a layer of type safety offered by TypeScript going forward. It is therefore prudent to remove the type casts and instead have TypeScript resolves types properly automatically.

### Desired solution

Remove type casts such as shown at https://github.com/sapphiredev/shapeshift/pull/40#discussion_r814748987 and ensure code compiles successfully.

### Alternatives considered

Continue to use type casts in the code.

### Additional context

Review comment from @vladfrangu https://github.com/sapphiredev/shapeshift/pull/40#discussion_r814748987

**Comment by vladfrangu** [comment]
There's no easy fix for this tbh, without probably overcomplicating code.
