### ISSUE TITLE
bug: Reshape is in the docs, but is nowhere in the code

### ISSUE THREAD

**Issue by Sly-Little-Fox** [sapphiredev/shapeshift#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When trying to use `s.string.reshape()`, TypeScript complains about that method not existing. A simple recursive `grep` shows that the method is only in README.md, but it nowhere in the code. 

### Steps To Reproduce

1. `grep reshape -r ./node_modules/@sapphire/shapeshift/dist/` (or `rg reshape ./node_modules/@sapphire/shapeshift/dist/`)
2. Command finds nothing

### Expected behavior

The method exists

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/69681150/159115320-20a827bd-3c44-4d71-ac3e-3dbedf09de1d.png)

**Comment by favna** [comment]
reshape has not yet been implemented and will be in v2.1.0

FYI github has search functionality. No need to grep. https://github.com/sapphiredev/shapeshift/search?q=reshape

**Comment by Sly-Little-Fox** [comment]
> reshape has not yet been implemented and will be in v2.1.0
> 
> FYI github has search functionality. No need to grep. https://github.com/sapphiredev/shapeshift/search?q=reshape

Oh, okay. You should add a notice about that. I use grep (mostly ripgrep though) because I find it convenient. ~~I'm addicted to console~~
