### ISSUE TITLE
bug: BaseError is not correctly exported

### ISSUE THREAD

**Issue by Hibanka** [sapphiredev/shapeshift#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Node v16, TypeScript, CommonJS, shapeshift 2.1.0

```ts
import { BaseError } from '@sapphire/shapeshift';

console.log(BaseError); // logs undefined
```

So the question is why BaseError is **undefined**?

And if this is normal behavior, then how can I check that the error was thrown by shapeshift? The original idea was to use `instanceof BaseError` since all other errors inherits from it

### Steps To Reproduce

1. Environment: Node v16, TypeScript, CommonJS, shapeshift 2.1.0
2. Import BaseError and log it into console

### Expected behavior

BaseError should be exported correctly 

OR

Tell me how to check that the error was thrown by shapeshift without instanceof BaseError 

### Additional context

Sorry if this is not a bug. I sent a such message to the Sapphire discord server but no response :(

**Comment by favna** [comment]
> So the question is why BaseError is undefined?

Because it is only exported as type. I'm surprised TS isn't screaming at you for importing BaseError and trying to use it as a value.

**Comment by favna** [comment]
This has been released to the `next` tag on npm. A `latest` release will be done after #78 is merged.
